title: "Aplicação CLI para Automação de Tarefas"
description: "Desenvolvi uma aplicação de linha de comando (CLI) para automatizar operações programáticas. A ferramenta foi projetada com foco em componentização e arquitetura modular, simplificando drasticamente a manutenção e a adição de novas funcionalidades. O resultado foi um ganho significativo de produtividade e uma redução na complexidade das tarefas para a equipe."
image: https://kktportfolio.blob.core.windows.net/public/portfolio/images/cli_Foto.png
url: "#"
tags: ["CLI", "Backend", "Automation", "Go", "F#"]
date: "2026"
